### ISSUE TITLE
username and password is involved in the official build while involving in build.gradle 

### ISSUE THREAD

**Issue by wylzt8384** [microsoftgraph/msgraph-sdk-android#102]
while using the implementation 'com.microsoft.graph:msgraph-sdk-android:1.5.0' in my project, when decompile code, there are username and password hardcoded in the BuildConfg.java, this is a security issue, so need to be address ASAP.
the username and password in the file is as below.
.field public static final PASSWORD:Ljava/lang/String; = "pass@word1"
.field public static final USERNAME:Ljava/lang/String; = "garthf@mod810997.onmicrosoft.com"

**Comment by MIchaelMainer** [comment]
First off, thank you for bringing this to our attention. That account is an old demo test account that is no longer valid.
