### ISSUE TITLE
GraphFatalServiceException when retrieving  a user's profile picture

### ISSUE THREAD

**Issue by Coopra** [microsoftgraph/msgraph-sdk-android#103]
When making a call with `client.getMe().getPhoto().buildRequest().get()` or `client.getMe().getPhoto().getContent().buildRequest().get()` I get a `GraphFatalServiceException` with a 501 response code stating this hasn't been implemented.

The underlying URL the SDK calls is [https://graph.microsoft.com/v1.0/me/photo](url). Are there plans to implement this in the SDK?

**Comment by baywet** [comment]
Hi everyone,
Thank you for the contribution, we have moved away from an android specific SDK to a [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java) and this repo will be archived very soon.
If you're still facing the same issue with the Java SDK, feel free to re-open an issue over there.
Closing.
