### ISSUE TITLE
ChunkedUploadProvider constructor size parameter int type limits upload to 2GB

### ISSUE THREAD

**Issue by SailReal** [microsoftgraph/msgraph-sdk-android#106]
Fore more details see https://github.com/microsoftgraph/msgraph-sdk-java/issues/211

I will create a PR soon

**Comment by baywet** [comment]
Hi everyone,
Thank you for the contribution, we have moved away from an android specific SDK to a [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java) and this repo will be archived very soon.
If you're still facing the same issue with the Java SDK, feel free to re-open an issue over there.
Closing.
