### ISSUE TITLE
Get AuthenticationProvider by accessToken

### ISSUE THREAD

**Issue by Abdallah4021** [microsoftgraph/msgraph-sdk-android#109]
building android application is connecting with server side, the mobile app takes the access token from server side. So can i create AuthenticationProvider by an access token ?

**Comment by baywet** [comment]
Hi everyone,
Thank you for the contribution, we have moved away from an android specific SDK to a [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java) and this repo will be archived very soon.
If you're still facing the same issue with the Java SDK, feel free to re-open an issue over there.
Closing.
