### ISSUE TITLE
Login failed with an account that I haven't used for a long time

### ISSUE THREAD

**Issue by 171008402** [microsoftgraph/msgraph-sdk-android#110]
I logged in with an account that I haven't used for a long time. After the Microsoft login interface came out, the account information was filled out, and I didn't get feedback from the successful login. When I logged in again, the Microsoft login screen never came out.

**Comment by baywet** [comment]
Hi everyone,
Thank you for the contribution, we have moved away from an android specific SDK to a [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java) and this repo will be archived very soon.
If you're still facing the same issue with the Java SDK, feel free to re-open an issue over there.
Closing.
