### ISSUE TITLE
This or msgraph-sdk-java for Android? 

### ISSUE THREAD

**Issue by Samhithgb** [microsoftgraph/msgraph-sdk-android#112]
Which is the suggested SDK for development in Android?

**Comment by baywet** [comment]
Hi everyone,
Thank you for the contribution, we have moved away from an android specific SDK to a [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java) and this repo will be archived very soon.
If you're still facing the same issue with the Java SDK, feel free to re-open an issue over there.
Closing.
