### ISSUE TITLE
Sample code to upload a file larger than 4 MB.

### ISSUE THREAD

**Issue by rmiragayasoluciones** [microsoftgraph/msgraph-sdk-android#113]
I cannot find the sample code to upload a file larger than 4 MB.

For < 4bm im using: 

**final byte[] bytesArray = new byte[(int) filePdfOriginal.length()];
            try {
                FileInputStream fis = new FileInputStream(filePdfOriginal);
                fis.read(bytesArray); //read file into bytes[]
                fis.close();

         this.mClientI        
                            .sites().byId(idSite)
                            .drives().byId(idDrive)
                            .items().byId(idFolder)
                            .children("fileName")
                            .content().buildRequest().put(bytesArray, callback());**

but I can't find the example to load the same file, if its size is> 4mb.

The documentation i found is [this](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online#create-an-upload-session) but nothing about Java/Android

**Comment by baywet** [comment]
Hi everyone,
Thank you for the contribution, we have moved away from an android specific SDK to a [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java) and this repo will be archived very soon.
If you're still facing the same issue with the Java SDK, feel free to re-open an issue over there.
Closing.
