### ISSUE TITLE
SMS Backup and Restore Error

### ISSUE THREAD

**Issue by clio44** [microsoftgraph/msgraph-sdk-android#115]
I'm sorry I don't know what I'm doing, but in trying to upload my SMS Backup and Restore file, it gave me an error and said to submit here.
So here I am.

This was the error message:

![Screenshot_20191213-194337_SMS Backup   Restore](https://user-images.githubusercontent.com/58868038/70840688-f7c5bd80-1de1-11ea-93a8-267405cb0d65.jpg)

**Comment by baywet** [comment]
Hi everyone,
Thank you for the contribution, we have moved away from an android specific SDK to a [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java) and this repo will be archived very soon.
If you're still facing the same issue with the Java SDK, feel free to re-open an issue over there.
Closing.
