### ISSUE TITLE
SMS Backup on Android 10 won't upload backups with onedrive

### ISSUE THREAD

**Issue by helenoftroy08** [microsoftgraph/msgraph-sdk-android#119]
SMS Backup is an app used to back up call logs and messages.  It works fine using google drive or box or even drop box.  Using one drive, 95% of the time it results in an "upload failed error."  it reports a long error message to report here, but i am unable to copy and paste it so i took a screen shot and have pasted it here.
![Screenshot_20200426-084117_SMS Backup   Restore](https://user-images.githubusercontent.com/64363926/80309642-f2b74880-879b-11ea-85d4-2c2f26987592.jpg)

Thanks in advance for any input or advice.

**Comment by baywet** [comment]
Hi everyone,
Thank you for the contribution, we have moved away from an android specific SDK to a [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java) and this repo will be archived very soon.
If you're still facing the same issue with the Java SDK, feel free to re-open an issue over there.
Closing.
