### ISSUE TITLE
Error thrown when one drive is not configured

### ISSUE THREAD

**Issue by josephkniestprometheanworld** [microsoftgraph/msgraph-sdk-android#120]
Is there a programmatic means of using the graph sdk to auto set-up one drive for a microsoft account that has not already done so? If one drive is not set up and we attempt to get the DriveItem root, the following function throws an exception:

 "com.microsoft.graph.generated.BaseDriveItemRequest" throws

com.microsoft.graph.http.GraphServiceException: Error code: itemNotFound\nError message: Item does not exist\n\nGET https:\/\/graph.microsoft.com\/v1.0\/me\/drive\/root\nSdkVersion : graph-java\/v1.7.1\nAuthorization : Bearer <>+[...]\n\n\n404 : Not Found\n[...]\n\n[Some information was truncated for brevity, enable debug logging for more details]\n\tat

is there any function that can be called given a user email that will automatically set up their one drive config?

**Comment by josephkniestprometheanworld** [comment]
For reference, the account I am testing with is "pwdev000@outlook.com"

**Comment by baywet** [comment]
Hi everyone,
Thank you for the contribution, we have moved away from an android specific SDK to a [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java) and this repo will be archived very soon.
If you're still facing the same issue with the Java SDK, feel free to re-open an issue over there.
Closing.
