### ISSUE TITLE
Not getting notified when the user changes his password in Exchange Contacts

### ISSUE THREAD

**Issue by Kiran521** [microsoftgraph/msgraph-sdk-android#121]
Graph API is working even user changes the  Password in Exchange Contacts. (Android SDK)

### Expected behavior
User not supposed to allow to access any sort of data (Create, update, All contacts etc...) once he changes his password in Exchange Contacts

### Actual behavior
User is able to access all sort of data (Create, update, All contacts etc...) once he changes his password in Exchange Contacts

### Steps to reproduce the behavior

Go to exchange contacts and change password
Try to create or update contacts, it's working.

**Comment by baywet** [comment]
Hi everyone,
Thank you for the contribution, we have moved away from an android specific SDK to a [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java) and this repo will be archived very soon.
If you're still facing the same issue with the Java SDK, feel free to re-open an issue over there.
Closing.
