### ISSUE TITLE
Upload a File

### ISSUE THREAD

**Issue by diogowbrito** [microsoftgraph/msgraph-sdk-android#15]
Is there a way to create a file and upload contents, such as [referenced here](http://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/item_uploadcontent)?

After having looked at the SDK code I didn't find a way to do so.

**Comment by peternied** [comment]
Thanks for the question @diogowbrito, OneDrive upload and download scenarios are supported, you can see a end-to-end example with this SDK with the [OneDrive Explorer](https://github.com/microsoftgraph/onedrive-explorer-android).

Upload a file, [full example here](https://github.com/microsoftgraph/onedrive-explorer-android/blob/master/app/src/main/java/com/microsoft/onedrive/apiexplorer/ItemFragment.java#L706):

``` java
final String parentItemId = // The id for the parent folder this item is being uploaded into
final String filename = // The name of the file being uploaded
final byte[] fileInMemory = // The contents of the file to upload

graphServiceClient
    .getMe()
    .getDrive()
    .getItems(parentItemId)
    .getChildren()
    .byId(filename)
    .getContent()
    .buildRequest()
    .put(fileInMemory,
        new IProgressCallback<DriveItem>() {
            @Override
            public void success(final DriveItem item) {
                // Handle success
            }

            @Override
            public void failure(final ClientException error) {
                // Handle failure
            }

            @Override
            public void progress(final long current, final long max) {
                // Handle progress updates
            }
        });
```

Download a file, [thumbnail example here](https://github.com/microsoftgraph/onedrive-explorer-android/blob/master/app/src/main/java/com/microsoft/onedrive/apiexplorer/DisplayItem.java#L80),

``` java
final String itemId = //The id of the item to download
new AsyncTask<Void, Void, Void>() {
    @Override
    protected Void doInBackground(Void... params) {
        final InputStream fileContents = graphServiceClient
                .getDrive()
                .getItems(itemId)
                .getContent()
                .buildRequest()
                .get();

        return null;
    }
};
```

**Comment by diogowbrito** [comment]
Thanks @peternied. Exactly what I was looking for.
