### ISSUE TITLE
Upload a File should be able to receive an InputStream

### ISSUE THREAD

**Issue by diogowbrito** [microsoftgraph/msgraph-sdk-android#16]
Right now, to upload a file a `byte[]` is required. This means the full contents of the file must be allocated in memory which may cause an `OutOfMemoryError`.

It would be a good enhancement to have the upload method receive an `InputStream` rather than a `byte[]`.

**Comment by thekindJose** [comment]
Hi, any update on this issue?

**Comment by peternied** [comment]
@joseal82 We would be happy to review a pull request for this functionality.  As of this time there is no planned support for InputStream in the SDK.

**Comment by iambmelt** [comment]
Large file upload introduced in #35 and released in `1.2.0`

Thanks @daboxu for implementation, integration, and review assist.

Question for @daboxu: is there usage documentation available anywhere for large-file support we could link to for anyone who comes across this issue?

**Comment by daboxu** [comment]
@iambmelt a section about uploading large file is here: https://github.com/OneDrive/onedrive-sdk-android/blob/master/docs/items.md#upload-a-large-file

**Comment by iambmelt** [comment]
@daboxu Thanks!
