### ISSUE TITLE
getThumbnailSize and getItemWithPath were deleted

### ISSUE THREAD

**Issue by peternied** [microsoftgraph/msgraph-sdk-android#24]
There was a couple of extensions methods that were deleted in the latest revisions of the SDK.
- getItemWithPath (See 3ea51cd38d3fd36265e3e246f1fc4cb94de13860)
- getThumbnailSize (See 134f503b4042b22075d530af6c871ca4c3015d60)

Could we get these added back and add unit tests to make sure we don't regress again?

(Found while building the [OneDrive Explorer for Android](https://github.com/microsoftgraph/onedrive-explorer-android))

**Comment by iambmelt** [comment]
Merged - thanks @peternied
