### ISSUE TITLE
getCreateLink to a DriveItem requires Files.ReadWrite scope

### ISSUE THREAD

**Issue by kumaraish** [microsoftgraph/msgraph-sdk-android#30]
As per my testing in accordance with the graph docs [here](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/item_createlink), the API [getCreateLink()](https://github.com/microsoftgraph/msgraph-sdk-android/blob/master/graphsdk/src/main/java/com/microsoft/graph/generated/BaseDriveItemRequestBuilder.java) requires `Files.ReadWrite` scope to work; otherwise, HTTP 403, `access denied` is returned.

IMHO, `getCreateLink` should work with `Files.Read` scope too (although with a restricted **view** only permission); this is currently how other cloud provider APIs work.

**Comment by peternied** [comment]
To leave feedback on this request please use [UserVoice for OneDrive](https://onedrive.uservoice.com/forums/262982-onedrive/category/89523-developer)
