### ISSUE TITLE
In GraphServiceClient builder, the method to set logger has private access.

### ISSUE THREAD

**Issue by kumaraish** [microsoftgraph/msgraph-sdk-android#42]
In `GraphServiceClient` builder, the method to set logger has private access. It should have public access like other setters of `GraphServiceClient.Builder`

https://github.com/microsoftgraph/msgraph-sdk-android/blob/master/graphsdk/src/main/java/com/microsoft/graph/extensions/GraphServiceClient.java#L90

**Comment by iambmelt** [comment]
Thanks for reporting this issue @kumaraish - as a workaround, you can set the `ILogger` instance through `IClientConfig`
