### ISSUE TITLE
Expose method setUseCaches on IHttpRequest

### ISSUE THREAD

**Issue by sbolotovms** [microsoftgraph/msgraph-sdk-android#49]
As stated in documentation:
https://developer.android.com/reference/java/net/URLConnection.html#setUseCaches(boolean)
You can set useCaches to true to allow URLConnection in Android to cache results. It would be great if you'd expose this method in IHttpRequest so that user won't have to do workaround setting and resetting defaultUseCaches value.

**Comment by caitlinrussell** [comment]
Thanks for the PR!
