### ISSUE TITLE
MeetingDuration in FindMeetingTimes doesn't serialize

### ISSUE THREAD

**Issue by ghost** [microsoftgraph/msgraph-sdk-android#54]
The issue is about serialization of ```meetingDuration``` parameter in ```IBaseUserRequestBuilder.getFindMeetingTimes``` method.
When it is set in the request to ```"PT30M"``` it gets serialized to ```{}```.

It is easy to check this problem by putting a debugger in ```DefaultSerializer.serializeObject``` method and check that ```serializableObject``` contains ```meetingDuration``` set and after Gson serialization ```outJsonTree``` always have the empty value.

Duration object is created with the following code:
```java
DatatypeFactory.newInstance().newDuration("PT30M")
```

**Comment by caitlinrussell** [comment]
This will go out with the next bugfix release. Thanks for finding this!
