### ISSUE TITLE
standard java support

### ISSUE THREAD

**Issue by davidmoten** [microsoftgraph/msgraph-sdk-android#60]
Hi
I don't see an msgraph-sdk-java, just this android project. 

Any plans for supporting java on the server/client rather than just Android? I see that the code for this project is largely generated. Could a similar approach be used to generate a standard java sdk as well?

Thanks

**Comment by caitlinrussell** [comment]
David, thanks for the feedback. This is something we have in the backlog to write.

**Comment by stacysimpson** [comment]
Hi, we are also interested in a pure java version of the client library. Could you give us an indication for how deep this project is on your backlog? Are we talking weeks/months/years?

It would help us determine whether we should delay or proceed with a limited OneDrive integration. Thanks.

**Comment by caitlinrussell** [comment]
Hi Stacy, we have this as a high priority item but unfortunately we cannot commit to any dates. It will likely be several months or more before this work is complete.

**Comment by stacysimpson** [comment]
OK, thanks for the update.
