### ISSUE TITLE
mobilePhone is single String instead of List

### ISSUE THREAD

**Issue by iljaX** [microsoftgraph/msgraph-sdk-android#61]
Hi, 

I think the mobilePhone field should  also be a List like homePhones/businessPhones.

    /**
     * The Home Phones.
	 * 
     */
    @SerializedName("homePhones")
    @Expose
    public java.util.List<String> homePhones;

    /**
     * The Mobile Phone.
	 * 
     */
    @SerializedName("mobilePhone")
    @Expose
    public String mobilePhone;

    /**
     * The Business Phones.
	 * 
     */
    @SerializedName("businessPhones")
    @Expose
    public java.util.List<String> businessPhones;

Thank you.
Best regards
Ilja

**Comment by caitlinrussell** [comment]
This is not defined by the SDK but by the [Graph service](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/user). Azure AD does not currently store multiple mobile phone numbers.
If you would like to see this as a feature, you can submit it to [UserVoice](https://feedback.azure.com/forums/169401-azure-active-directory)
