### ISSUE TITLE
Use ChunkedUploadProvider asynchronously

### ISSUE THREAD

**Issue by NLLAPPS** [microsoftgraph/msgraph-sdk-android#70]
Hi, is there any sample for uploading large files?
There is this sample 

`client.getMe() .getDrive()
                                    .getRoot()
                                    .getItemWithPath("me.png")
                                    .getContent()
                                    .buildRequest()
                                    .put(file, callback);`

As you would imagine, it would be trouble some to `put` large files.
How would one achieve that?
Thanks.

**Comment by caitlinrussell** [comment]
To accomplish this, you will want to use [Resumable Upload](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/driveitem_createuploadsession). There is currently no example in the SDK, but you will want to use `createUploadSession` on your item and create a new `ChunkedUploadProvider` to process your request in chunks.

**Comment by caitlinrussell** [comment]
In pseudocode:

```java
DriveItemUploadableProperties props = new DriveItemUploadableProperties();
// Set file name, size, etc.
client.getMe().getDrive().getRoot().getItemWithPath("me.png").createUploadSession(props).buildRequest().post();

ChunkedUploadProvider provider = new ChunkedUploadProvider<T>(session, client, stream, size, class);
provider.upload(options, callback, configs);
```

**Comment by NLLAPPS** [comment]
Thank you. I'll try. While ı have you, there seems to be a lot of different ads related to OneDrive and  authentication.

As I understand from what I have read so far it they graph sdk is the way forward. Is that correct?

**Comment by caitlinrussell** [comment]
Yes, that is what we are recommending. However, we are not yet at full parity with Azure AD, so I would verify in the Graph docs that your scenarios are supported. We should be near or at parity with OneDrive.

**Comment by MIchaelMainer** [comment]
@NLLAPPS In case it helps, here's the commit in the .Net client library where we implemented large file uploads.
https://github.com/microsoftgraph/msgraph-sdk-dotnet/commit/7c037cf15413b73d1ad7b52ee027a703f4b63be1#diff-374daffefc443a2b383da1d332b730c6

**Comment by NLLAPPS** [comment]
Cheers, it should not be too card to convert

**Comment by NLLAPPS** [comment]
Hi guys, I am not sure if I am doing this right. ChunkedUploadProvider.upload is a blocking method that runs on main thread with callback.

How would one use an AsyncTask or another thread while waiting for the call back. The only way I can think of is to block the AysncTask with another variable within the task that changes according to IProgressCallback result. 

Wouldn't it be simpler if ChunkedUploadProvider.upload done on another thread?

**Comment by NLLAPPS** [comment]
Any feedback about the above issue?

**Comment by NLLAPPS** [comment]
Anyone? @cbales @MIchaelMainer

**Comment by ronnafaye** [comment]
Hi @cbales ,
I was able to create ChunkedUploadProvider but I'm having error when I tried the upload function.
May I know what is the int configs parameter? 
Maybe you can provide a sample snippet of this function. 
Your help is much appreciated. @_@

**Comment by kbboss** [comment]
@PAYong  finally,how you make it work? about uploading large file with microsoft api. I got the same problem

**Comment by NLLAPPS** [comment]
Any updates to this issue?

**Comment by ohs0612** [comment]
I would like to know how to upload file by using CreateUploadSession from msgraph-sdk-android OneDrive SDK.

**Comment by baywet** [comment]
Hi everyone,
Thank you for the contribution, we have moved away from an android specific SDK to a [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java) and this repo will be archived very soon.
If you're still facing the same issue with the Java SDK, feel free to re-open an issue over there.
Closing.
