### ISSUE TITLE
Too many methods and too many files in "com/microsoft/graph/generated"

### ISSUE THREAD

**Issue by jaredsburrows** [microsoftgraph/msgraph-sdk-android#71]
Why are there over 2k files in a single Java package? Are these auto generated? If so, I would highly suggest this be broken down into smaller packages and possibly using an annotation process to only generate the files needed based on the clients needs.

There are way too many methods for this library: http://www.methodscount.com/?lib=com.microsoft.graph%3Amsgraph-sdk-android%3A1.2%2B

<img width="1090" alt="screen shot 2017-12-21 at 8 54 15 pm" src="https://user-images.githubusercontent.com/1739848/34282182-98854ee6-e691-11e7-9c7d-8d0bd8e06249.png">

**Comment by caitlinrussell** [comment]
I agree, this library is getting very bulky for the average use case. All but a handful are autogenerated according to metadata provided by the Graph API. We are currently working with the API team to enable namespacing. This will let us break up the library into smaller packages that the developer can bring in as necessary. Generating SDKs on demand by the developer is another great idea and we have not done a lot of investigation into this work yet. It would also rely on namespacing to work correctly.

**Comment by baywet** [comment]
Hi everyone,
Thank you for the contribution, we have moved away from an android specific SDK to a [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java) and this repo will be archived very soon.
If you're still facing the same issue with the Java SDK, feel free to re-open an issue over there.
Closing.
