### ISSUE TITLE
isError(GraphErrorCodes.ItemNotFound) does not work for events and photos

### ISSUE THREAD

**Issue by x0b** [microsoftgraph/msgraph-sdk-android#80]
When requesting a non-existing item, the exception that is thrown does not have ```mErrorCode``` or ```mError``` set and will not match isError(any GraphErrorCode).

Example Urls:
```https://graph.microsoft.com/v1.0/users/{userid}/photo/$value```
```https://graph.microsoft.com/v1.0/users/{userid}/events/{non-existing-item}```

I've browsed the exception throwing code a bit and it seems that most 4xx errors will not be correctly identified because the actual error response is not correctly deserialized.

This is not caught in [the test](https://github.com/microsoftgraph/msgraph-sdk-android/blob/bb0fa603b11c34a9df8b3436535a07c26231ad95/graphsdk/src/androidTest/java/com/microsoft/graph/http/GraphServiceExceptionTests.java) due to the test assuming correct deserialization.

**Comment by MIchaelMainer** [comment]
Thank you for reporting this.
760334

**Comment by baywet** [comment]
Hi everyone,
Thank you for the contribution, we have moved away from an android specific SDK to a [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java) and this repo will be archived very soon.
If you're still facing the same issue with the Java SDK, feel free to re-open an issue over there.
Closing.
