### ISSUE TITLE
Deserialization error: wrong case on LocationType.DEFAULT since 1.7.0

### ISSUE THREAD

**Issue by x0b** [microsoftgraph/msgraph-sdk-android#82]
Enum Value ```LocationType.DEFAULT``` has the wrong case and causes log pollution with
```
The following value default could not be recognized as a member of the enum
```

Caused by case mismatch between 
https://github.com/microsoftgraph/msgraph-sdk-android/blob/762b81e801bd53b477c14d7023562281f52fa29f/graphsdk/src/main/java/com/microsoft/graph/extensions/LocationType.java#L26

and Graph API delivering the value as lowercase ```"default"```.

Graph SDK Version: ```1.7.0```

**Comment by deepak2016** [comment]
@x0b can you provide an example code snippet, where are you are facing this issue?

**Comment by deepak2016** [comment]
Not able to repro, hence closing this issue. Kindly reopen if you still face this issue.
