### ISSUE TITLE
gradle.properties

### ISSUE THREAD

**Issue by ayatm** [microsoftgraph/msgraph-sdk-android#85]
What are the values that I have to assign to those variable in the gradle.properties file:
ClientId="CLIENT_ID"
Username="USERNAME"
Password="PASSWORD"

**Comment by MIchaelMainer** [comment]
I'm not sure how those are used. Perhaps to run the end to end tests.

ClientId: You'll get that from an app registration, https://github.com/microsoftgraph/msgraph-sdk-android#21-register-your-application
Username and password: I expect that this is using the deprecated password flow. I have no idea whether this is still allowed.

**Comment by ayatm** [comment]
My problem is I want to include the SDK source code directly in my project. But unfortunately, all the request not work when I include the SDK source code to my project. but when I add 
 implementation 'com.microsoft.graph:msgraph-sdk-android:1.5.0' to gradle file they work, but that not what I want. do you have any hints?

**Comment by MIchaelMainer** [comment]
I'm sorry that I don't have any hints for you. If you are using source directly in your project, have you considered using the https://github.com/microsoftgraph/msgraph-sdk-java client?

**Comment by ayatm** [comment]
Thank you for your help, The problem was I used the sample code and the graph sdk     "implementation 'com.microsoft.graph:msgraph-sdk-android:1.5.0' "
When I used the sdk as source code it was not working, I am not sure what was the problem but it seems the SDK source code version is 1.7.0 and maybe it doesn't compatible to the sample code. So I implemented the code from the link that you sent before and it works now, Thank you for help.
