### ISSUE TITLE
Search request

### ISSUE THREAD

**Issue by ayatm** [microsoftgraph/msgraph-sdk-android#86]
I am trying to search for emails by sender email address as the following
    requestOptions.add(new QueryOption("$search=","\"from:ayat@hhhhhh.com\""));
               client
                    .getMe()
                    .getMessages()
                    .buildRequest(requestOptions)
                    .get(new ICallback<IMessageCollectionPage>() {....}

but that does not work!
Any idea?

**Comment by Glennmen** [comment]
Not sure if it is the same for emails but for contacts I use this:
```java
final List<Option> options = new LinkedList<Option>();
options.add(new QueryOption("filter", "startswith(displayName,'" + text + "') or startswith(givenName,'" + text + "') or startswith(surname,'" + text + "')"));
```

I would assume you can do this:
```java
requestOptions.add(new QueryOption("filter","from/emailAddress/address eq 'ayat@hhhhhh.com'"));
```
Or if you want to keep using the search param maybe this (I haven't tested it myself):
```java
requestOptions.add(new QueryOption("search","from:ayat@hhhhhh.com"));
```

**Comment by ayatm** [comment]
Thank you so much, this one requestOptions.add(new QueryOption("filter","from/emailAddress/address eq 'ayat@hhhhhh.com'")); works with me

**Comment by baywet** [comment]
Hi everyone,
Thank you for the contribution, we have moved away from an android specific SDK to a [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java) and this repo will be archived very soon.
If you're still facing the same issue with the Java SDK, feel free to re-open an issue over there.
Closing.
