### ISSUE TITLE
Messages Count

### ISSUE THREAD

**Issue by ayatm** [microsoftgraph/msgraph-sdk-android#91]
I want to ask if there any way I can get the number of unread messages, the following query returns the messages: 
options.add(new QueryOption("filter","IsRead eq "+false));
            getMessagesCountRequestAndResponse(options);

But I just want the count number.

**Comment by NakulSabharwal** [comment]
Hi
Try adding $count=true for getting number of unread messages.

**Comment by NakulSabharwal** [comment]
We are considering your issue as resolved. Please reopen the issue and comment if any further help is required. Thanks.
