### ISSUE TITLE
Use This API or onedrive-sdk-android for accessing OneDrive on Android ?

### ISSUE THREAD

**Issue by bubbleguuum** [microsoftgraph/msgraph-sdk-android#94]
I've used the now retired Live Connect API Android SDK to access OneDrive on Android.
I'm a bit perplexed at the SDK I should now use. Is it this SDK or onedrive-sdk-android (which has not seen a commit since July 2017) ? I do not want to invest effort in another possibly dead SDK.

**Comment by MIchaelMainer** [comment]
@bubbleguuum I'm sorry for the confusing lack of communication on which library you should use for Android long-term. We were supposed to provide this comm already but I see we haven't. Our plan is to make the [msgraph-sdk-java](https://github.com/microsoftgraph/msgraph-sdk-java) library the library to use on Android and Java. This will enable us to have long-term support for both platforms.

Adding other folks who may have a more appropriate communication on this: @darrelmiller @deepak2016

**Comment by bubbleguuum** [comment]
Thanks, for the time being I went with onedrive-sdk-android. It works fine for my limited needs and if I need to update to a new SDK it should not be very difficult as the underlying objects (at the json level) are the same. But it is sure confusing for anyone wanting to add OneDrive support to an Android app. It would be sure great if the MS web page for OneDrive Android development had clear guidance on what to use!

**Comment by baywet** [comment]
Hi everyone,
Thank you for the contribution, we have moved away from an android specific SDK to a [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java) and this repo will be archived very soon.
If you're still facing the same issue with the Java SDK, feel free to re-open an issue over there.
Closing.
