### ISSUE TITLE
Retreiving the file content in pdf formar failing

### ISSUE THREAD

**Issue by ammyatmail** [microsoftgraph/msgraph-sdk-android#95]
Hi,

I am using ADAL lib for authentication purpose. Post authentication I am calling MS Graph api to retreive the content of the office format files(.doc, .ppt) in pdf format. But the api call is failling. Can you suggest what I am doing wrong here?

02-02 16:22:27.832 2603-2681/com.azuresamples.azureadsampleapp.azureadsampleapp D/DefaultHttpProvider[sendRequestInternal] - 314: Response json
02-02 16:22:28.012 2603-2678/com.azuresamples.azureadsampleapp.azureadsampleapp D/DefaultSerializer[deserializeObject] - 71: Deserializing type GraphErrorResponse
02-02 16:22:28.052 2603-2678/com.azuresamples.azureadsampleapp.azureadsampleapp E/DefaultHttpProvider[sendRequestInternal] - 333: OneDrive Service exception GET https://graph.microsoft.com/v1.0/me/drive/root:/aa.pptx:/content
02-02 16:22:28.082 2603-2678/com.azuresamples.azureadsampleapp.azureadsampleapp E/DefaultHttpProvider[sendRequestInternal] - 333: SdkVersion : graph-android-v1.7.0
02-02 16:22:28.142 2603-2678/com.azuresamples.azureadsampleapp.azureadsampleapp E/DefaultHttpProvider[sendRequestInternal] - 333: Authorization : Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI[...]
02-02 16:22:28.212 2603-2678/com.azuresamples.azureadsampleapp.azureadsampleapp D/dalvikvm: GC_FOR_ALLOC freed 430K, 17% free 3827K/4608K, paused 70ms, total 71ms
02-02 16:22:28.242 2603-2678/com.azuresamples.azureadsampleapp.azureadsampleapp E/DefaultHttpProvider[sendRequestInternal] - 333: 404 : Not Found
    [...]
02-02 16:22:28.252 2603-2678/com.azuresamples.azureadsampleapp.azureadsampleapp E/DefaultHttpProvider[sendRequestInternal] - 333: [Some information was truncated for brevity, enable debug logging for more details]
02-02 16:22:28.262 2603-2678/com.azuresamples.azureadsampleapp.azureadsampleapp E/DefaultHttpProvider[sendRequestInternal] - 333: Throwable detail: 
    com.microsoft.graph.http.GraphServiceException: GET https://graph.microsoft.com/v1.0/me/drive/root:/aa.pptx:/content
    SdkVersion : graph-android-v1.7.0
    Authorization : Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI[...]
    
    
    404 : Not Found
    [...]
    
    [Some information was truncated for brevity, enable debug logging for more details]
        at com.microsoft.graph.http.DefaultHttpProvider.handleErrorResponse(DefaultHttpProvider.java:357)
        at com.microsoft.graph.http.DefaultHttpProvider.sendRequestInternal(DefaultHttpProvider.java:294)
        at com.microsoft.graph.http.DefaultHttpProvider.access$000(DefaultHttpProvider.java:49)
        at com.microsoft.graph.http.DefaultHttpProvider$1.run(DefaultHttpProvider.java:141)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
02-02 16:22:28.262 2603-2678/com.azuresamples.azureadsampleapp.azureadsampleapp D/DefaultExecutors[performOnForeground] - 125: Starting foreground task, current active count:0, with exception com.microsoft.graph.http.GraphServiceException: GET https://graph.microsoft.com/v1.0/me/drive/root:/aa.pptx:/content
02-02 16:22:28.272 2603-2678/com.azuresamples.azureadsampleapp.azureadsampleapp D/DefaultExecutors[performOnForeground] - 125: SdkVersion : graph-android-v1.7.0
02-02 16:22:28.312 2603-2678/com.azuresamples.azureadsampleapp.azureadsampleapp D/DefaultExecutors[performOnForeground] - 125:
[log_msgraph.txt](https://github.com/microsoftgraph/msgraph-sdk-android/files/2829242/log_msgraph.txt)

**Comment by baywet** [comment]
Hi everyone,
Thank you for the contribution, we have moved away from an android specific SDK to a [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java) and this repo will be archived very soon.
If you're still facing the same issue with the Java SDK, feel free to re-open an issue over there.
Closing.
