### ISSUE TITLE
isError(GraphErrorCodes.ItemNotFound) does not work for files

### ISSUE THREAD

**Issue by gerritbeuze** [microsoftgraph/msgraph-sdk-android#97]
Similar to issue #80: but want to add that this also not working for files, making the graph-api useless for file sync.

Copy from #80:
 When requesting a non-existing item, the exception that is thrown does not have `mErrorCode` or `mError` set and will not match isError(any GraphErrorCode).

Example call:
`getClient().getMe().getDrive().getItems(notExistingDriveId).buildRequest().get(...`

I've browsed the exception throwing code a bit and it seems that most 4xx errors will not be correctly identified because the actual error response is not correctly deserialized.

**Comment by baywet** [comment]
Hi everyone,
Thank you for the contribution, we have moved away from an android specific SDK to a [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java) and this repo will be archived very soon.
If you're still facing the same issue with the Java SDK, feel free to re-open an issue over there.
Closing.
