### ISSUE TITLE
failed to Cancel the upload session

### ISSUE THREAD

**Issue by AlexChen0527** [microsoftgraph/msgraph-sdk-android#98]
uploadURL = new URL(uploadSession.uploadUrl);
HttpURLConnection connection = (HttpURLConnection)uploadURL.openConnection();
connection.setRequestMethod("DELETE");
connection.connect();

It's not work, how to cancel the upload Session?

**Comment by baywet** [comment]
Hi everyone,
Thank you for the contribution, we have moved away from an android specific SDK to a [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java) and this repo will be archived very soon.
If you're still facing the same issue with the Java SDK, feel free to re-open an issue over there.
Closing.
