### ISSUE TITLE
Upload to OneDrive failed : [This is an unexpected error from Graph, please report this at https://github.com/microsoftgraph/msgraph-sdk-android/issues]

### ISSUE THREAD

**Issue by jebeld17** [microsoftgraph/msgraph-sdk-android#99]
The following is an error report I'm getting from the Graph API in a third-party program by Carbonite, SMS Backup & Restore when trying to upload a file change to my personal OneDrive account.
I've contacted the development team behind the "SMS Backup & Restore" app and they seem certain the issue resides on the Graph API end.

Here the message:

_____

Upload to OneDrive failed : [This is an unexpected error from Graph, please report this at https://github.com/microsoftgraph/msgraph-sdk-android/issues]
PUT https://api.onedrive.com/rup/5908a542ea8723db/eyJSZXNvdXJjZUlEIjoiNTkwOEE1NDJFQTg3MjNEQiEyMTMzMjEiLCJSZWxhdGlvbnNoaXBOYW1lIjoic21zX3UxMS0yLnhtbCJ9/4mldA9xu5m1vY_XrSuyFz7MBsn_ok4Effz7bhIlj6id8-x4PHOsg-babBvM94DQ4UeDWtZi3EilVisDGRqkBs-iThc22OM0QEsrvjDW9TG2I8/eyJOYW1lIjoic21zX3UxMS0yLnhtbCJ9/4wDyYj3w2joilkb7QBUqByp_IjRg--UO9x0n-hB3kEKVnKziF5Ll7A8N6WocNcqS48ghi5FpKgX0nLSIbdTGMmuDlCzc9b2oNNySV_pEkbOF4kSfcNU0zNrkNp_2jLU0UALfAOWUuYvkEdox5yvSqn2zEzfWNzcQPAQfKtP2y8WU7XjfzFTVHFVu1L1S71yC84eYZ3HysB5BF3OtGdfb1IWnjDfQw-cLyMO-iPTT3tlvL0GiB7HYWOgRrKhF33nQalC5EIkFg_RGSnSzu5rONXMbCNORR4lT_dljtiQ_QVgzYiMtEU4_FX_ouCXptHj5kvQTkpT91_rW2G-uwe5x8Fy7tgYhLpnxapUA-cvFT4wqiUohGuwO7eW9XgU6D9m6ADMjrx8j3qZQL9ww_gNIts7NixCvYzIZj6s0laxWDaX4RHN_F_CUSIR1KV5UgtZSRW_B81tH-EC_IbX9rrFkuJMznPJ4kbo2aDdaYp5SSEaE6BUV2lwkK54eYeQtoz8PGtPYH7Kidag8X0SxqkCaXV5FKSHROXJG7ck_qgNCqwNO-6QJX4dRdrvKfyfB9g22gt
SdkVersion : graph-android-v1.7.0
Content-Range : bytes 1441136640-1443102719/7813755021
Authorization : Bearer EwCAA8l6BAAURSN/FHlDW5xN74t6GzbtsBBeBUYAAYWJFWRpmEAzDxIm+ostyzMa6aum56a56YMSeEAMpReB6gqwrDmJax53Qv7eFFGGzLnKbVP7yi6BRyWKl+DrB7begyYgfVcTZQOJJq2yiYG7RUwOyUXHwZzpMLwgA9O+rfT7dFsYaGX/JfKLhkLJpgZYNe4qF8T9iCHOHMQJaoCrbE2hw9PSlD8tw9qB/7Vj9ABg/9vME+HvN1ULHcSbYXmo5mSgLFtIwfyc6IpKLy3FayzGGDGNiNmpyZUBRYZp+sxC/Z7dLQn2qrGgyOpcJuggTESI8U3QJ3G+cpu+wnrtmGjCspA/8Dn0hz/ZcoLT9C8CMqJ1jpwbq+Xa2R6jDDMDZgAACBPYe/DUNbe6UALnGs8Whi8JQRahPXyNigRd26UN0OR0CdF92eHLrRnayJcPi7Wr83qzQS9F9wi77c3x0t8SwZH8SdzgtChFMyap1RPqdayjJN+vyA8nk9PHws9Y9AmrRrynrZ6zbPpnrLdO1G8Q/q+tRovUhMR3uBeS29WWleIiPYXVKcEuh/Fll778LErERb/FEMw90Lyo1Afga8tfMsvr1XAAOSu0tVfGVvzRBy/vIfSa/WxTuJhTns8BOq+Wx3UMwxHlA5PiC6XIi7nEt4ck8JuHslChyQ08DhVCV0Ktvhn/xQg0Ug6qQZNDaidx3Bu8pg26Cunizo93PKzAd4ohlQUeUGGz1z/ukGpo9GE0y4umHxv36GyuTumc+dh/r7mHFk0ypcEaLs3Q0wkg7AUvH/cTEyjPNpJnn9jg7njQk8y38yVJOrkGnVP4VIYVkSXsF8Uj7LrQThxmyQllG1RdFkreGNc4sOaaL81//lx4ZBw77vyIzzaRam6xctvpLg8x1RRi5wUZl69yzU++VzT9UjIJknTGVDNS7/179DGNoH0ASt4g77OoHiB6zQkl/jtpyPrpJz/aktUjDKM5eyrtea1PP0Yf94kYgnyWEK87/iNCq39vsXVStsXbDVWcu8EYbpA92S7oLAn3SGn0WsqEXyGI8YBttn5hIcoKR1ArFzOL3twcdangaTYOUQJ/dg309LGSCcSpY5gUqemClWiTtwXlzfshQaxmiuoiQzgQPEGii0eIc9XgCMTE4KggZXUHAWAJ7CShQJL3IEQLxrCaIn5yyKfAq5aQeQI=

500 : Internal Server Error
X-QosStats : {"ApiId":0,"ResultType":0,"SourcePropertyId":42,"TargetPropertyId":274}
X-ThrowSite : 15bf.1333
WWW-Authenticate : Bearer realm="OneDriveAPI", error="invalid_token", error_description="Invalid auth token"
X-AsmVersion : UNKNOWN; 19.191.211.2003
P3P : CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
X-Android-Received-Millis : 1550599843557
X-MSEdge-Ref : Ref A: 634816D8F70149A5BD0C3B59BC1A9DDE Ref B: MIAEDGE1609 Ref C: 2019-02-19T18:10:44Z
X-MSNSERVER : DM5SCH103160117
Date : Tue, 19 Feb 2019 18:10:44 GMT
X-Android-Selected-Protocol : http/1.1
Strict-Transport-Security : max-age=31536000; includeSubDomains
X-Android-Response-Source : NETWORK 500
X-Android-Sent-Millis : 1550599823512
Content-Type : application/json; charset=utf-8
{
   "error": {
      "code": "generalException",
      "message": "General Exception While Processing"
   }
}
: com.microsoft.graph.core.ClientException: [This is an unexpected error from Graph, please report this at https://github.com/microsoftgraph/msgraph-sdk-android/issues]
PUT https://api.onedrive.com/rup/5908a542ea8723db/eyJSZXNvdXJjZUlEIjoiNTkwOEE1NDJFQTg3MjNEQiEyMTMzMjEiLCJSZWxhdGlvbnNoaXBOYW1lIjoic21zX3UxMS0yLnhtbCJ9/4mldA9xu5m1vY_XrSuyFz7MBsn_ok4Effz7bhIlj6id8-x4PHOsg-babBvM94DQ4UeDWtZi3EilVisDGRqkBs-iThc22OM0QEsrvjDW9TG2I8/eyJOYW1lIjoic21zX3UxMS0yLnhtbCJ9/4wDyYj3w2joilkb7QBUqByp_IjRg--UO9x0n-hB3kEKVnKziF5Ll7A8N6WocNcqS48ghi5FpKgX0nLSIbdTGMmuDlCzc9b2oNNySV_pEkbOF4kSfcNU0zNrkNp_2jLU0UALfAOWUuYvkEdox5yvSqn2zEzfWNzcQPAQfKtP2y8WU7XjfzFTVHFVu1L1S71yC84eYZ3HysB5BF3OtGdfb1IWnjDfQw-cLyMO-iPTT3tlvL0GiB7HYWOgRrKhF33nQalC5EIkFg_RGSnSzu5rONXMbCNORR4lT_dljtiQ_QVgzYiMtEU4_FX_ouCXptHj5kvQTkpT91_rW2G-uwe5x8Fy7tgYhLpnxapUA-cvFT4wqiUohGuwO7eW9XgU6D9m6ADMjrx8j3qZQL9ww_gNIts7NixCvYzIZj6s0laxWDaX4RHN_F_CUSIR1KV5UgtZSRW_B81tH-EC_IbX9rrFkuJMznPJ4kbo2aDdaYp5SSEaE6BUV2lwkK54eYeQtoz8PGtPYH7Kidag8X0SxqkCaXV5FKSHROXJG7ck_qgNCqwNO-6QJX4dRdrvKfyfB9g22gt
SdkVersion : graph-android-v1.7.0
Content-Range : bytes 1441136640-1443102719/7813755021
Authorization : Bearer EwCAA8l6BAAURSN/FHlDW5xN74t6GzbtsBBeBUYAAYWJFWRpmEAzDxIm+ostyzMa6aum56a56YMSeEAMpReB6gqwrDmJax53Qv7eFFGGzLnKbVP7yi6BRyWKl+DrB7begyYgfVcTZQOJJq2yiYG7RUwOyUXHwZzpMLwgA9O+rfT7dFsYaGX/JfKLhkLJpgZYNe4qF8T9iCHOHMQJaoCrbE2hw9PSlD8tw9qB/7Vj9ABg/9vME+HvN1ULHcSbYXmo5mSgLFtIwfyc6IpKLy3FayzGGDGNiNmpyZUBRYZp+sxC/Z7dLQn2qrGgyOpcJuggTESI8U3QJ3G+cpu+wnrtmGjCspA/8Dn0hz/ZcoLT9C8CMqJ1jpwbq+Xa2R6jDDMDZgAACBPYe/DUNbe6UALnGs8Whi8JQRahPXyNigRd26UN0OR0CdF92eHLrRnayJcPi7Wr83qzQS9F9wi77c3x0t8SwZH8SdzgtChFMyap1RPqdayjJN+vyA8nk9PHws9Y9AmrRrynrZ6zbPpnrLdO1G8Q/q+tRovUhMR3uBeS29WWleIiPYXVKcEuh/Fll778LErERb/FEMw90Lyo1Afg

**Comment by jebeld17** [comment]
The bug has occurred again this week, including today.
Please see the error message I've received below:

"
[This is an unexpected error from Graph, please report this at https://github.com/microsoftgraph/msgraph-sdk-android/issues]
PUT https://api.onedrive.com/rup/5908a542ea8723db/eyJSZXNvdXJjZUlEIjoiNTkwOEE1NDJFQTg3MjNEQiEyMTU0ODYiLCJSZWxhdGlvbnNoaXBOYW1lIjoic21zX3UxMS0yLnhtbCJ9/4m8SGk-wBwGu-M9_hYNK-dyR33d2-5K6nLGwV5HOobNjAIbqJcVZQnRo0w_OvCeFSu2zhC6tgV9C6rgEaA9dACj4XhmJ3qDlDlM01CHX51fQQ/eyJOYW1lIjoic21zX3UxMS0yLnhtbCJ9/4wYBDBCjft3WtwQENejOxM4Qb7ecOOQ7s-DKH6HfxxQt5_1Kha8yR6r_CF1jSgvJRWs2FvpueO0NunAdRuvyf0u0fTyUIxvthLAmLZKvmFqUZi5jE7Jga5CCzUwg6DpJtGOcQfwgB15EH8zdbmpt8c96NbGnin-8nYU4iQdtPxoRqwf1ZaM5iyZMzl6ynQa5B3ofMN1Tbpbxv4hA3q1--0mEg_8y88SEhW9e4mykqTdbr5kZJbFOwsYwG_DLSNipGBYxhI_WlEgEyRDWH_i3uxJLGM4W-idfaisCFjwPhQKwAGtTq0cri-MMnc3J1Lt_mrjOOePcTcwf-6rR2PxaXeBj0MIGsIVwIh0cYdNKv8Pf2etdeWhZFAxsyUbcYrluAsCfWLLe-uVDbF_Ryx8MZ3gDuxncLPgHLbyJskYNQSqvAoJnvZuktjCqhrvMdH0C5p9YeNFQCGcK_xywasmTPS7tcJZhclNYrSmVD2yvUpBtQFfhV_zMHFeDOI7UacEVufCCvRvuVVDzBPWZqWUivtgpGT5Ui6gRQcVMO8bKMKMJ1leTYqkR5cFTEpHg4FbPF3
SdkVersion : graph-android-v1.7.0
Content-Range : bytes 7801405440-7803371519/8095055046
Authorization : Bearer EwCAA8l6BAAURSN/FHlDW5xN74t6GzbtsBBeBUYAAQad4lrYnX3hjW/+F6AKwKcbolu+a+N1rO2K3oIjq9fV0erhRh2+TnXr9cevRAhhl9twqbZTf6t2QngHPzNfO7NmKCK2AUeonQ8Tq67+mhL6qrIEZ8KxQP89Eg7cIe/pfos6ls5xaYrQOgzcWomvCo5FAZnS7Xhq+WSz4UrE+w7qNj/GZTIZEHXKrZGpQbSjeNDivk0grq/55cAgD2waRCZ7IbyqHW/4+NSBIMQwKIyJXzoCx2c1ly/ma9e+urt3AxM/Yotr72p+KvE/MyaF1ZN43eB9FDNfMJY8V8NMoLh7WALCk9n/S/B1m0ygmYJRkh8pssiy0LefLcyasRhMpFUDZgAACI36g7w0xJSlUAL8r7Jnl+0F5wuinSdyDyoQWJ/339zu8qOHWlbrBYvYxIou81TDCkW9bZnWXbcr6N/SFdPTMuGwT+/viKWjRrvLzbnktgzO7epPbWcUlkbEpXC52d8D0fOf/v4ERiO8RjHG12r8lnTRRUuT51pux+sZIbztaRcNerBiodAhWUANPdIc18QNQEoH+l3+u182STnLQYWXQrv4k7cMbGA9YO+0W724w3+K74D6DZ1fvF2K4Hpag9bMoInDGqpAbCFU3myEqXkE51JON0HxxnhSc395N22kDhdXdoQhqQFikHtfZVnaeC7Yr7IKOiNPjderBD1dtUGUnL+4ASjvaFdkYc1xSm83xsmOCj0fO0j4CzUE1SifpmE7ZjwL6BukIlag6NiQ88NqKTjY4HJH78YUPhSW5AxTOsQb8sVj8y9mHREFtAKHl8S7Z+KzsmkFpiyhYlen9WysPBuQHjmoPqWmvBvJcPszpPCnLg4sm8crQEB+8oc6Ijc8gyNmWYLsqQdqE++zzAD3jkwOQb7/69pzIOWaWImSAz18QZYhHwwikTTDoXfwNIaA1TsMbKpFeQPiokv+qneTxe8ZddnVsMFmWpYZmipMlowEeCYuymn0IfkWlOoE/O+FaUR7NOk4OlYnDSM4qtwfWQHe9/o6XrrfCV92U2XOUDv5HnIMV72jvoledXEDCQnhBs/H73C88BNMDe0ShqeLNfaYXdXBgkiiYmDwvhyFM5BhxEHuHnPSBbd7HLUQlMMK2cF6Pe0+QmukJllkjxiwGejaeaFyC8rKzATMeQI=


500 : Internal Server Error
X-QosStats : {"ApiId":0,"ResultType":0,"SourcePropertyId":42,"TargetPropertyId":274}
X-ThrowSite : 15bf.1333
WWW-Authenticate : Bearer realm="OneDriveAPI", error="invalid_token", error_description="Invalid auth token"
X-AsmVersion : UNKNOWN; 19.205.304.2003
P3P : CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
X-Android-Received-Millis : 1552454532437
X-MSEdge-Ref : Ref A: 9764D3A2B2774D10960D78A67CABA951 Ref B: MIAEDGE1519 Ref C: 2019-03-13T05:21:54Z
X-MSNSERVER : DM5SCH102221220
Date : Wed, 13 Mar 2019 05:22:13 GMT
X-Android-Selected-Protocol : http/1.1
Strict-Transport-Security : max-age=31536000; includeSubDomains
X-Android-Response-Source : NETWORK 500
X-Android-Sent-Millis : 1552454512803
Content-Type : application/json; charset=utf-8
{
   "error": {
      "code": "generalException",
      "message": "General Exception While Processing"
   }
}
"

**Comment by remort** [comment]
Faced exactly the same issue working with onedrive api directly. May be it is a permissions/scopes issue ?

update: The issue was about scopes and proper auth flow.
First I used wrong auth flow documnt:
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/graph-oauth?view=odsp-graph-online

Finally I found this auth flow document which works for me (pay attention to scopes and other parameters in both initial auth and auth code requests):
https://docs.microsoft.com/en-us/graph/auth-v2-user?context=graph%2Fapi%2F1.0&view=graph-rest-1.0

**Comment by baywet** [comment]
Hi everyone,
Thank you for the contribution, we have moved away from an android specific SDK to a [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java) and this repo will be archived very soon.
If you're still facing the same issue with the Java SDK, feel free to re-open an issue over there.
Closing.
